version: '3'

services:

  oeplannerapi:
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    build:
      context: src/backend
      dockerfile: oeplannerapi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq

  oeplannerworker:
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_TRANSPORT=RMQ
    build:
      context: src/backend
      dockerfile: oeplannerworker/Dockerfile
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=5555
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"