name: OEPlannerAPI

on:
  push:
    paths:
    - 'src/BACKEND/OEPlannerAPI/**'
    - '.github/workflows/api-deploy.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      working-directory: src/BACKEND/OEPlannerAPI
      run: poetry install

    - name: Build app
      working-directory: src/BACKEND/OEPlannerAPI
      run: poetry build

    - name: Unpack artifact
      run: |
        tar -xzf ./src/backend/OEPlannerAPI/dist/oeplannerapi-0.1.0.tar.gz
        rm ./src/backend/OEPlannerAPI/dist/oeplannerapi-0.1.0.tar.gz  

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.API_APP_SERVICE_NAME }}
        package: ./src/BACKEND/OEPlannerAPI/dist
        resource-group-name: ${{ vars.RG_NAME }}
        startup-command: "uvicorn main:app --host 0.0.0.0 --port 8080"