name: Azure Resource Deployment

on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/deploy-azure-resources.yml'
    - 'deploy/bicep/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: 'subscription'
        region: ${{ vars.LOCATION }}
        template: ./deploy//bicep/main.bicep
        parameters:
          rgName=${{ vars.RG_NAME }}
          location=${{ vars.LOCATION }}
          uiAppServiceName=${{ vars.UI_APP_SERVICE_NAME }}
          workerAppServiceName=${{ vars.WORKER_APP_SERVICE_NAME }}
          apiAppServiceName=${{ vars.API_APP_SERVICE_NAME }}
          appInsightsName=${{ vars.APP_INSIGHTS_NAME }}
          logAnalyticsName=${{ vars.LOG_ANALYTICS_NAME }}
          appServicePlanName=${{ vars.APP_SERVICE_PLAN_NAME }}