name: OE Planner UI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ui-deploy.yml'
      - 'src/UI/OEPlanner/**'

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: npm install and build
      working-directory: ./src/UI/OEPlanner
      run: |
        npm install
        npm run build

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'    

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.UI_APP_SERVICE_NAME }}
        package: ./src/UI/OEPlanner/dist/oeplanner
        resource-group-name: ${{ vars.RG_NAME }}