name: OEPlannerWorker

on:
  push:
    paths:
    - 'src/BACKEND/OEPlannerAPI/**'
    - 'src/BACKEND/OEPlannerWorker/**'
    - '.github/workflows/worker-deploy.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Configure poetry and install dependencies
      working-directory: ./src/BACKEND/OEPlannerWorker
      run: |
        python -m venv antenv
        source antenv/bin/activate
        poetry export -f requirements.txt --output requirements.txt
        antenv/bin/pip install -r requirements.txt 

    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.WORKER_APP_SERVICE_NAME }}
        package: ./src/BACKEND/OEPlannerWorker
        resource-group-name: ${{ vars.RG_NAME }}
        startup-command: "python -m celery -A oeplannerworker.celery_app worker --loglevel=info"